---
- name: Create /etc/ansible
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    mode: '0644'
  
- name: Copy ansible.cfg
  ansible.builtin.copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: '0644'

- name: Create systemd ansible-update service
  ansible.builtin.template:
    src: ansible-update.service.j2
    dest: /lib/systemd/system/ansible-update.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Systemd daemon-reload
    - Enable ansible-update.service

- name: Create systemd ansible-update timer
  ansible.builtin.template:
    src: ansible-update.timer.j2
    dest: /lib/systemd/system/ansible-update.timer
    owner: root
    group: root
    mode: '0644'
  notify:
    - Systemd daemon-reload
    - Enable ansible-update.timer
