---
# tasks file for common
- name: Install pre-requisite
  ansible.builtin.include_tasks: prerequisite.yml
- name: Manage ansible-pull
  ansible.builtin.include_tasks: ansible.yml
- name: Manage users
  ansible.builtin.include_tasks: users.yml
- name: Manage ssh keys
  ansible.builtin.include_tasks: ssh.yml
