---
- name: Copy ssh key to user
  ansible.posix.authorized_key:
    user: "{{ common_admin_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - ~/.ssh/id_ed25519.pub
