---
# tasks file for docker
- name: Uninstall Docker
  include_tasks: teardown.yml
  tags:
    - teardown

- name: Uninstall old version
  include_tasks: uninstall_old.yml

- name: Prerequisite
  include_tasks: prerequisite.yml

- name: Install docker
  ansible.builtin.apt:
    pkg: 
      - docker-ce 
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin 
    state: present
