---
# tasks file for raspberry
- name: Update package
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade raspberry pi
  become: true
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Perfom reboot
  become: true
  ansible.builtin.reboot:
    post_reboot_delay: 30
    test_command: "whoami"
  when: reboot_required.stat.exists
