---
- name: Check if k3s is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Download and install k3s
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  when: "'master' in inventory_hostname"

- name: Read K3s node token
  slurp:
    src: /var/lib/rancher/k3s/server/token
  register: k3s_token
  when: "'master' in inventory_hostname"

- name: Save token for agents
  set_fact:
    k3s_join_token: "{{ k3s_token.content | b64decode | trim }}"
  run_once: true
  when: "k3s_binary.stat.exists and 'master' in inventory_hostname"
  delegate_to: localhost
