---
- name: Create systemd service
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    mode: '0644'
    owner: root
    group: root

- name: Restart K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted

- name: Get token from server
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/token
  register: k3s_token

- name: Set fact for cluster token
  ansible.builtin.set_fact:
    k3s_token: "{{ k3s_token.content | b64decode }}"

