user_list:
  - name: reaper-backup
    state: present
    authorized_keys:
      # NixOs Key
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICNV9Ew6IaAmQ5oiN3gUBAM6qXwKiGBvj/lwt81WJvot jphetphoumy@nixos"
      # Windows Key
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGATpiQj4UJZOYYi5Xbuby9IfK4Ad6Fc0OSRbjqYz3Cw jphet@Workstatation"
