---
# tasks file for gitea
- name: Create gitea user
  ansible.builtin.user:
    name: "{{ gitea_user }}"
    comment: gitea user 
    create_home: false
    shell: /usr/sbin/nologin 
- name: Create gitea folder
  ansible.builtin.file:
    path: "{{ gitea_data_dir }}" 
    recurse: true
    state: directory
    mode: 0750  

- name: Create gitea config folder
  ansible.builtin.file:
    path: "{{ gitea_config_dir }}" 
    recurse: true
    state: directory
    mode: 0750  

- name: Copy Dockerfile on remote host
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ gitea_folder }}/docker-compose.yml" 
    owner: root 
    group: root 
    mode: "0644"

- name: Start gitea
  community.docker.docker_compose_v2:
    project_src: "{{ gitea_folder }}" 
    state: present
