---
plugin: community.general.proxmox
user: root@pam
# token_id: root_api
# token_secret: "{{ lookup('ansible.builtin.env', 'PROXMOX_ROOT_TOKEN_API') }}"
password: "{{ lookup('ansible.builtin.env', 'PROXMOX_ROOT_PASSWORD') }}"
url: https://192.168.1.213:8006
want_facts: true
want_proxmox_nodes_ansible_host: true
validate_certs: false
keyed_groups:
  # proxmox_tags_parsed is an example of a fact only returned when 'want_facts=true'
  - key: proxmox_tags_parsed
    separator: _
    prefix: group
compose:
  ansible_user: "'root' if proxmox_vmtype == 'lxc' else 'jphetphoumy'"
  ansible_python_interpreter: "'/usr/bin/python3.11'"
  ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ansible.utils.ipaddr('address')
  proxmox2:
    ansible_python_interpreter: /usr/bin/python3.11
