---
- name: Create packer user
  ansible.builtin.include_tasks: packer.yml
  when: "'teardown' not in ansible_run_tags"
- name: Destroy packer user
  ansible.builtin.include_tasks: packer_teardown.yml
  tags:
    - never
    - teardown
