---
- name: Delete packer user
  become: true
  ansible.builtin.shell: >
    set -o pipefail
    pveum user list | grep -q {{ packer_username }}
    || echo "USER EXISTS"
    && pveum user delete {{ packer_username }}
  register: pveum_user
  changed_when: pveum_user.stdout != "USER EXISTS"
  tags:
    - never
    - teardown
