---
- name: Create packer user
  become: true
  shell: >
    pveum user list | grep -q {{ packer_username }}
    && echo "USER DOES NOT EXIST"
    || pveum user add {{ packer_username }}
  register: pveum_user
  changed_when: pveum_user.stdout != "USER DOES NOT EXIST"
- name: Add user {{ packer_username }} to {{ packer_user_role }} 
  become: true
  shell: >
    pveum acl list | grep -q {{ packer_username }}
    && echo "NO ACL FOR USER"
    || pveum aclmod / -user {{ packer_username }} -role {{ packer_user_role }}
  register: pveum_acl_mod
  changed_when: pveum_acl_mod.stdout != "NO ACL FOR USER"

- name: Generate an API token for the user
  become: true
  shell: >
    pveum user token list {{ packer_username }} | grep -q {{ packer_token_name }}
    && echo "TOKEN DOES NOT EXIST"
    || pveum user token add {{ packer_username }} {{ packer_token_name }} -privsep {{ packer_token_privilege }}
  register: pveum_token
  changed_when: pveum_token.stdout != "TOKEN DOES NOT EXIST"

- name: Parse the token value
  set_fact:
    packer_api_token: "{{ pveum_token.stdout | regex_search('.\\svalue\\s+.\\s([a-f0-9\\-]+)\\s+.', '\\1')}}"
  when: pveum_token.changed

- name: Display the API token
  debug:
    msg: "Your API token is: {{ packer_api_token }}"
  when: pveum_token.changed
