---
# handlers file for common
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable ansible-update.timer 
  ansible.builtin.systemd:
    name: ansible-update.timer
    state: started
    enabled: true

- name: Enable ansible-update.service
  ansible.builtin.systemd:
    name: ansible-update.service
    enabled: true
