---
- name: Create jenkin network
  community.docker.docker_network:
    name: jenkins
  when: "jenkins_master is defined and jenkins_master == True"

- name: Create jenkins-docker
  community.docker.docker_container:
    name: jenkins-docker
    image: docker:dind
    detach: true
    privileged: true
    env:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      - name: jenkins
        aliases: docker
    published_ports:
      - 2376:2376
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
  when: "jenkins_master is defined and jenkins_master == True"

- name: Create /opt/jenkins
  ansible.builtin.file:
    path: /opt/jenkins
    state: directory
    mode: 0750

- name: Copy Dockerfile on remote host
  ansible.builtin.template:
    src: Dockerfile.jenkins-master.j2
    dest: /opt/jenkins/Dockerfile
    owner: root
    group: root
    mode: "0644"
  when: "jenkins_master is defined and jenkins_master == True"

- name: Copy configuration as code
  ansible.builtin.template:
    src: casc.yaml.j2
    dest: /opt/jenkins/casc.yaml
    owner: root
    group: root
    mode: "0644"
  when: "jenkins_master is defined and jenkins_master == True"

- name: Build custom image
  community.docker.docker_image_build:
    name: jenkins-blueocean:2.462.2-1
    path: /opt/jenkins
    dockerfile: Dockerfile
  when: "jenkins_master is defined and jenkins_master == True"

- name: Create jenkins-docker
  community.docker.docker_container:
    name: jenkins-blueocean
    image: jenkins-blueocean:2.462.2-1
    restart_policy: on-failure
    detach: true
    env:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    networks:
      - name: jenkins
    published_ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - /opt/jenkins/casc.yaml:/var/jenkins_home/casc.yaml
      - jenkins-docker-certs:/certs/client:ro
  when: "jenkins_master is defined and jenkins_master == True"
