---
# tasks file for jenkins
- name: Create jenkins user
  ansible.builtin.user:
    name: jenkins
    comment: manage jenkins
    create_home: true
    shell: /bin/bash
    group: docker

- name: Manage jenkins docker container
  ansible.builtin.include_tasks: docker.yml
